## Opening PNAD Data

[PNAD](https://www.ibge.gov.br/estatisticas/sociais/populacao/9171-pesquisa-nacional-por-amostra-de-domicilios-continua-mensal.html) stands for Pesquisa Nacional por Amostra de Domicílio (The National Household Sample Survey), a survey carried out by the Brazilian Institute of Geography and Statistics (IBGE) on a sample of Brazilian households that, for having multiple purposes, investigates various socioeconomic characteristics of society, such as population, education, work , income, housing, social security, migration, fertility, marriage, health, nutrition, and many others.

In [1]:
import pandas as pd

In [2]:
f = open('C:/Users/andre/Documents/Thesis/Thesis Project/Novas planilhas até 22-12-2020/pnad/PNADC_042020/PNADC_042020.txt', 'w')
print(f.read())

UnsupportedOperation: not readable

In [4]:
with open('C:/Users/andre/Documents/Thesis/Thesis Project/Novas planilhas até 22-12-2020/pnad/PNADC_042020/PNADC_042020.txt', 'w') as f:
    contents = f.read()
    print(contents)

UnsupportedOperation: not readable

In [5]:
#when trying to open the text file, as if it were a normal txt file, in either way it won't open

Another way could be to open the text file on [sublime text](https://www.sublimetext.com) and save it on csv

In [6]:
pnad4thtrimester2020csv = pd.read_csv('C:/Users/andre/Documents/Thesis/Thesis Project/Novas planilhas até 22-12-2020/pnad/PNADC_042020/PNADC_042020.csv', sep='delimiter', header=None)

<ipython-input-6-dad99cde1f7a>:1: ParserWarning: Falling back to the 'python' engine because the 'c' engine does not support regex separators (separators > 1 char and different from '\s+' are interpreted as regex); you can avoid this warning by specifying engine='python'.
  pnad4thtrimester2020csv = pd.read_csv('C:/Users/andre/Documents/Thesis/Thesis Project/Novas planilhas até 22-12-2020/pnad/PNADC_042020/PNADC_042020.csv', sep='delimiter', header=None)

The data can be downloaded [here](https://www.ibge.gov.br/estatisticas/downloads-estatisticas.html?caminho=Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Trimestral/Microdados/2020).
The 1st file corresponds to the 1st trimester of 2020, the 2nd file, 2nd trimester, and the same logic for the 3rd and 4th files.

In [7]:
pnad4thtrimester2020csv.shape

(335566, 1)

In [8]:
pnad4thtrimester2020csv.head(3)

                                                   0
0  202041111  11000001611100110108311000083.40224...
1  202041111  11000001611100110108311000083.40224...
2  202041111  11000001611100110108311000083.40224...

In [9]:
#If the file is opened on csv or txt, it will not work because it will have only one column and it won't be readable. 
#It needs to be opened with fwf from the text file format, fwf stands for 'fixed width files'.

Here's the documentation on [fwf](https://pandas.pydata.org/pandas-docs/version/0.22/generated/pandas.read_fwf.html)

In [10]:
pnad4thtrimester2020 = pd.read_fwf('C:/Users/andre/Documents/Thesis/Thesis Project/Novas planilhas até 22-12-2020/pnad/PNADC_042020/PNADC_042020.txt',header=None, dtype=str)

In [11]:
pnad4thtrimester2020.shape

(335566, 31)

In [12]:
pnad4thtrimester2020.head(3)

,0,1,2,3,4,5,6,7,8,9,...,21,22,23,24,25,26,27,28,29,30
0,202041111,11000001611100110108311000083.40224763000126.9...,NaN,1,072,105,21,NaN,NaN,191123 69000,...,2,NaN,NaN,NaN,NaN,01063205311,NaN,110107091331000010450000104510000104500001045,040,04033
1,202041111,11000001611100110108311000083.40224763000126.9...,NaN,1,10,101,21,NaN,NaN,152233 48071,...,2,NaN,NaN,NaN,NaN,03063410411,NaN,110104051331000010450000104510000104500001045,040,04033
2,202041111,11000001611100110108311000083.40224763000126.9...,06,01,NaN,NaN,22222,NaN,NaN,NaN,...,NaN,2,2,NaN,NaN,220306330942 2,NaN,NaN,2,NaN

In [13]:
#Python does not know the width of the columns
#It's also important to type 'dtype = str', so python does not try to find any other kinds of data type objects besides strings.

In [14]:
#There's the need to pass a list 'width', because python does not know how large each column in the data is;
#these numbers below came from the data dictionary, from the column 'tamanho', which means size.

PNAD's data dictionary can be downloaded in this [page](https://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Trimestral/Microdados/Documentacao/) or directly [here](https://ftp.ibge.gov.br/Trabalho_e_Rendimento/Pesquisa_Nacional_por_Amostra_de_Domicilios_continua/Trimestral/Microdados/Documentacao/Dicionario_e_input_20210617.zip), both pages are on IBGE's website.

In [15]:
width = [4,1,2,2,2,9,7,2,2,1,1,1,15,15,9,3,2,2,2,1,2,2,4,3,1,1,1,1,2,2,1,1,1,2,1,1,1,2,2,1,1,1,1,2,1,1,1,1,1,1,1,1,1,1,1,1,
2,2,2,1,4,1,1,5,1,1,1,1,1,1,2,1,1,2,2,1,1,1,1,1,2,2,1,1,1,1,1,1,1,1,1,1,1,1,1,1,8,1,1,8,1,1,1,1,1,8,1,1,8,3,3,1,2,
2,2,4,1,1,5,1,1,1,1,1,1,1,1,8,1,1,8,1,1,1,1,1,8,1,1,8,3,3,1,1,1,1,8,1,1,8,1,1,1,1,1,1,8,1,1,8,3,3,1,1,1,1,1,2,1,1,
1,2,1,2,1,2,2,2,1,1,1,1,2,2,1,1,2,1,1,1,1,1,1,1,1,1,2,2,2,1,1,1,1,8,8,1,8,8,1,1,3,3,3,3,3,1,1]

In [16]:
pnad4thtrimester2020 = pd.read_fwf('C:/Users/andre/Documents/Thesis/Thesis Project/Novas planilhas até 22-12-2020/pnad/PNADC_042020/PNADC_042020.txt', widths=width, header=None, dtype=str)

In [17]:
pd.set_option('display.max_columns', None)

In [18]:
pnad4thtrimester2020.head(3)

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18,19,20,21,22,23,24,25,26,27,28,29,30,31,32,33,34,35,36,37,38,39,40,41,42,43,44,45,46,47,48,49,50,51,52,53,54,55,56,57,58,59,60,61,62,63,64,65,66,67,68,69,70,71,72,73,74,75,76,77,78,79,80,81,82,83,84,85,86,87,88,89,90,91,92,93,94,95,96,97,98,99,100,101,102,103,104,105,106,107,108,109,110,111,112,113,114,115,116,117,118,119,120,121,122,123,124,125,126,127,128,129,130,131,132,133,134,135,136,137,138,139,140,141,142,143,144,145,146,147,148,149,150,151,152,153,154,155,156,157,158,159,160,161,162,163,164,165,166,167,168,169,170,171,172,173,174,175,176,177,178,179,180,181,182,183,184,185,186,187,188,189,190,191,192,193,194,195,196,197,198,199,200,201,202,203,204,205,206,207,208,209,210,211,212,213,214,215,216
0,2020,4,11,11,NaN,110000016,1110011,01,08,3,1,1,000083.40224763,000126.91052794,000542168,111,06,01,01,2,16,05,1981,039,4,1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,07,2,NaN,NaN,1,05,NaN,NaN,2,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,9112,3,NaN,69000,NaN,2,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,NaN,15,NaN,1,1,NaN,NaN,2,NaN,NaN,NaN,1,NaN,1,1,2,00001045,NaN,NaN,NaN,NaN,NaN,1,1,2,00001045,NaN,NaN,NaN,040,040,4,NaN,NaN,03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01,06,3,2,05,3,1,1,NaN,NaN,NaN,NaN,1,1,01,07,09,1,3,3,1,00001045,00001045,1,00001045,00001045,NaN,NaN,040,NaN,NaN,NaN,040,3,3
1,2020,4,11,11,NaN,110000016,1110011,01,08,3,1,1,000083.40224763,000126.91052794,000542168,111,06,02,05,2,12,06,2000,020,4,1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,10,NaN,NaN,NaN,1,01,NaN,NaN,2,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,5223,3,NaN,48071,NaN,2,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,4,NaN,NaN,NaN,1,1,NaN,NaN,2,NaN,NaN,NaN,1,NaN,1,1,2,00001045,NaN,NaN,NaN,NaN,NaN,1,1,2,00001045,NaN,NaN,NaN,040,040,4,NaN,NaN,02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03,06,3,4,10,4,1,1,NaN,NaN,NaN,NaN,1,1,01,04,05,1,3,3,1,00001045,00001045,1,00001045,00001045,NaN,NaN,040,NaN,NaN,NaN,040,3,3
2,2020,4,11,11,NaN,110000016,1110011,01,08,3,1,1,000083.40224763,000126.91052794,000542168,111,06,03,05,2,15,05,2004,016,4,1,1,2,NaN,06,NaN,NaN,NaN,01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,03,06,3,3,09,4,2,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
#By looking at the data dictionary, on the columns variables, each variable needs to be passed into a list with .columns,
#which names the columns.

In [20]:
pnad4thtrimester2020.columns = ['Ano','Trimestre', 'UF', 'CAPITAL','RM_RIDE','UPA', 'Estrato', 'V1008', 'V1014','V1016', 
                                'V1022','V1023', 'V1027', 'V1028','V1029', 'posest', 'V2001','V2003','V2005','V2007','V2008',
                                'V20081', 'V20082','V2009','V2010','V3001','V3002','V3002A','V3003','V3003A','V3004','V3005',
                                'V3005A','V3006','V3006A','V3007','V3008','V3009','V3009A','V3010','V3011','V3011A','V3012',
                                'V3013','V3013A','V3013B','V3014','V4001','V4002','V4003','V4004','V4005','V4006','V4006A',
                                'V4007','V4008','V40081','V40082','V40083','V4009','V4010','V4012','V4012','V40121','V4013',
                                'V40132','V40132A','V4014','V4015','V40151','V401511','V401512','V4016','V40161','V40162',
                                'V40163','V4017','V40171','V401711','V4018','V40181','V40182','V40183','V4019','V4020',
                                'V4021','V4022','V4024','V4025','V4026','V4027','V4028','V4029','V4032','V4033','V40331'
                                'V403311','V403312','V40332','V403321','V403322','V40333','V403331','V4034','V40341',
                                'V403411','V403412','V40342','V403421','V403422','V4039','V4039C','V4040','V40401','V40402',
                                'V40403','V4041','V4043','V40431','V4044','V4045','V4046','V4047','V4048','V4049','V4050',
                                'V40501','V405011','V405012','V40502','V405021','V405022','V40503','V405031','V4051','V40511',
                                'V405111','V405112','V40512','V405121','V405122','V4056','V4056C','V4057','V4058','V40581',
                                'V405811','V405812','V40582','V405821','V405822','V40583','V405831','V40584','V4059','V40591',
                                'V405911','V405912','V40592','V405921','V405922','V4062','V4062C','V4063','V4063A',
                                'V4064','V4064A','V4071','V4072','V4072A','V4073','V4074','V4074A','V4075A','V4075A1',
                                'V4076','V40761','V40762','V40763','V4077','V4078','V4078A','V4082','VD2002','VD2003','VD2004',
                                'VD3004','VD3005','VD3006','VD4001','VD4002','VD4003','VD4004','VD4004A','VD4005','VD4007',
                                'VD4008','VD4009','VD4010','VD4011','VD4012','VD4013','VD4014','VD4015','VD4016','VD4017',
                                'VD4018','VD4019','VD4020','VD4023','VD4030','VD4031','VD4032','VD4033','VD4034','VD4035',
                                'VD4036','VD4037']

In [21]:
pnad4thtrimester2020.head(3)

,Ano,Trimestre,UF,CAPITAL,RM_RIDE,UPA,Estrato,V1008,V1014,V1016,V1022,V1023,V1027,V1028,V1029,posest,V2001,V2003,V2005,V2007,V2008,V20081,V20082,V2009,V2010,V3001,V3002,V3002A,V3003,V3003A,V3004,V3005,V3005A,V3006,V3006A,V3007,V3008,V3009,V3009A,V3010,V3011,V3011A,V3012,V3013,V3013A,V3013B,V3014,V4001,V4002,V4003,V4004,V4005,V4006,V4006A,V4007,V4008,V40081,V40082,V40083,V4009,V4010,V4012,V4012,V40121,V4013,V40132,V40132A,V4014,V4015,V40151,V401511,V401512,V4016,V40161,V40162,V40163,V4017,V40171,V401711,V4018,V40181,V40182,V40183,V4019,V4020,V4021,V4022,V4024,V4025,V4026,V4027,V4028,V4029,V4032,V4033,V40331V403311,V403312,V40332,V403321,V403322,V40333,V403331,V4034,V40341,V403411,V403412,V40342,V403421,V403422,V4039,V4039C,V4040,V40401,V40402,V40403,V4041,V4043,V40431,V4044,V4045,V4046,V4047,V4048,V4049,V4050,V40501,V405011,V405012,V40502,V405021,V405022,V40503,V405031,V4051,V40511,V405111,V405112,V40512,V405121,V405122,V4056,V4056C,V4057,V4058,V40581,V405811,V405812,V40582,V405821,V405822,V40583,V405831,V40584,V4059,V40591,V405911,V405912,V40592,V405921,V405922,V4062,V4062C,V4063,V4063A,V4064,V4064A,V4071,V4072,V4072A,V4073,V4074,V4074A,V4075A,V4075A1,V4076,V40761,V40762,V40763,V4077,V4078,V4078A,V4082,VD2002,VD2003,VD2004,VD3004,VD3005,VD3006,VD4001,VD4002,VD4003,VD4004,VD4004A,VD4005,VD4007,VD4008,VD4009,VD4010,VD4011,VD4012,VD4013,VD4014,VD4015,VD4016,VD4017,VD4018,VD4019,VD4020,VD4023,VD4030,VD4031,VD4032,VD4033,VD4034,VD4035,VD4036,VD4037
0,2020,4,11,11,NaN,110000016,1110011,01,08,3,1,1,000083.40224763,000126.91052794,000542168,111,06,01,01,2,16,05,1981,039,4,1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,07,2,NaN,NaN,1,05,NaN,NaN,2,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,9112,3,NaN,69000,NaN,2,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3,NaN,NaN,15,NaN,1,1,NaN,NaN,2,NaN,NaN,NaN,1,NaN,1,1,2,00001045,NaN,NaN,NaN,NaN,NaN,1,1,2,00001045,NaN,NaN,NaN,040,040,4,NaN,NaN,03,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,01,06,3,2,05,3,1,1,NaN,NaN,NaN,NaN,1,1,01,07,09,1,3,3,1,00001045,00001045,1,00001045,00001045,NaN,NaN,040,NaN,NaN,NaN,040,3,3
1,2020,4,11,11,NaN,110000016,1110011,01,08,3,1,1,000083.40224763,000126.91052794,000542168,111,06,02,05,2,12,06,2000,020,4,1,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,NaN,10,NaN,NaN,NaN,1,01,NaN,NaN,2,1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,5223,3,NaN,48071,NaN,2,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,1,4,NaN,NaN,NaN,1,1,NaN,NaN,2,NaN,NaN,NaN,1,NaN,1,1,2,00001045,NaN,NaN,NaN,NaN,NaN,1,1,2,00001045,NaN,NaN,NaN,040,040,4,NaN,NaN,02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,03,06,3,4,10,4,1,1,NaN,NaN,NaN,NaN,1,1,01,04,05,1,3,3,1,00001045,00001045,1,00001045,00001045,NaN,NaN,040,NaN,NaN,NaN,040,3,3
2,2020,4,11,11,NaN,110000016,1110011,01,08,3,1,1,000083.40224763,000126.91052794,000542168,111,06,03,05,2,15,05,2004,016,4,1,1,2,NaN,06,NaN,NaN,NaN,01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,2,2,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,2,03,06,3,3,09,4,2,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [22]:
#Just checking the variable's unique values to see if it makes sense with the data dictionary, and it does.

In [23]:
pnad4thtrimester2020['V1022'].unique()

array(['1', '2'], dtype=object)

In [24]:
pnad4thtrimester2020['V1023'].unique()

array(['1', '4', '2', '3'], dtype=object)

In [25]:
pnad4thtrimester2020['UF'].unique()

array(['11', '12', '13', '14', '15', '16', '17', '21', '22', '23', '24',
       '25', '26', '27', '28', '29', '31', '32', '33', '35', '41', '42',
       '43', '50', '51', '52', '53'], dtype=object)

In [26]:
pnad4thtrimester2020['CAPITAL'].unique()

array(['11', nan, '12', '13', '14', '15', '16', '17', '21', '22', '23',
       '24', '25', '26', '27', '28', '29', '31', '32', '33', '35', '41',
       '42', '43', '50', '51', '52', '53'], dtype=object)

In [27]:
pnad4thtrimester2020['RM_RIDE'].unique()

array([nan, '13', '15', '16', '21', '22', '23', '24', '25', '26', '27',
       '28', '29', '31', '32', '33', '35', '41', '42', '43', '51', '52'],
      dtype=object)

In [28]:
#There are many variables to rename, what I would do, is to select some variables looking at the dictionary and then renaming it,
#intead of renaming all variables.

In [29]:
#The example below selects four variables just as an example. Usually to analyze the data someone would probably select 20-50 
#variables, but it's much better renaming 20-50 variables than about 400 variables. And there's the need to rename 
#them only once.

In [30]:
pnad4thtrimester2020selectedcolumns = pnad4thtrimester2020[['V2001','V2003','V2005','V2007']]

In [31]:
pnad4thtrimester2020selectedcolumns.rename({'V2001':'numberofhouseholds', 'V2003': 'ordernumber','V2005': 'relationtohousehold', 'V2007':'sex'}, axis = 1, inplace = True)

C:\Users\andre\Anaconda3\lib\site-packages\pandas\core\frame.py:4441: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  return super().rename(

In [32]:
pnad4thtrimester2020selectedcolumns

       numberofhouseholds ordernumber relationtohousehold sex
0                      06          01                  01   2
1                      06          02                  05   2
2                      06          03                  05   2
3                      06          04                  08   1
4                      06          05                  08   2
...                   ...         ...                 ...  ..
335561                 02          01                  01   1
335562                 02          02                  02   2
335563                 03          01                  01   1
335564                 03          02                  02   2
335565                 03          03                  04   2

[335566 rows x 4 columns]

In [33]:
#There's also the need to look at the dictionary in order to interpret, for example, sex has number 1 or 2, according to the 
#dictionary 1 is masculine and 2 is feminine. These four selected variables is just for an example, any variable can be chosen.

Part of this code I found [here](https://medium.com/data-hackers/microdados-em-python-um-pacote-para-ler-dados-da-pnad-e-pof-e254cf18477d). The library mentioned on the link does not work for the year 2020, the year that I needed. I also found another [page](https://gist.github.com/jpmvbastos/d20e91d3a49c655af815c8188059f4ff) with python code to open pnad, but it did not work for me.